### ISSUE TITLE
[DR] sBTC devenv quirks

### ISSUE THREAD

**Issue by kenrogers** [stacks-network/sbtc#273]
### Expected Behavior

Ideal behavior here is that users can just run `./build.sh` and then `./up.sh` and everything just works and is ready to go.

### Actual Behavior

I've had to implement a few funky workarounds to get everything working. Here is a list of things that would be nice to work through:

- Specifically in PR #260 when running `./up.sh` the API will fail to run because it is unhealthy. This can be resolved by manually spinning up the Stacks explorer, stacks API, sbtc, and bridge, I think this is related to how long the devnet takes to start mining blocks
- Would be great to have sbtc contract deployment be part of the startup process so devs don't have to deploy, then take sbtc down and back up

### Steps to Reproduce

Clons sbtc repo and follow current getting started guide.

**Comment by friedger** [comment]
Define "everything" :-)

Note, you don't need to run `build.sh` before. You can just run `up.sh`, if needed everything is build.

The deployment part is covered in #231

**Comment by CAGS295** [comment]
`up.sh` won't restart services if they are already running. If your service breaks, calling `up.sh` again will hardly fix anything. It will only run missing services; more is often needed to return your node to a healthy state. Moreover, It's up to the user to clean up services after using them before calling `up.sh` again. Nevertheless, It should not break unless you are fiddling with it, and as the devenv it is, you should break it, and should know when it breaks so that you can spin a new fresh copy. 

I do agree with you; it should work out of the box. The tricky part is defining 'everything' as Friedger said.

**Comment by friedger** [comment]
The unhealthy check is to be removed.

Closing this as duplicate. Feel free to reopen.
