### ISSUE TITLE
[Feature]: Validate bitcoin transaction sign requests

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc#286]
### Context
In #285 the logic for responding to bitcoin transaction sign requests were introduced. In that PR, the signers accept all requests. However, we should ensure that the signers only respond to valid sign request. A sign request is considered valid for a signer to sign if:

1. All deposit requests consumed by the bitcoin transaction are accepted by the signer.
2. All withdraw requests fulfilled by the bitcoin transaction are accepted by the signer.
3. The apportioned transaction fee for each request does not exceed any `max_fee`.
6. Each deposit request input has an associated amount that is greater than their assessed fee.
7. There is at least 3 blocks left before the depositor can reclaim their funds.

### Definition of done
The transaction signer only acknowledges valid bitcoin transactions.

**Comment by cylewitruk** [comment]
> All deposit requests consumed by the bitcoin transaction are accepted by the signer.
All withdraw requests fulfilled by the bitcoin transaction are accepted by the signer.

@djordon hm, so based on the above, the signer not liking a single deposit/withdrawal (which maybe was accepted by all of the other signers) will cause the signer to withhold its vote on the entire sweep transaction, right? Feels kinda like the signer should sign anyway if they're part of the minority vote, otherwise if this happens continuously and sporadically it could deadlock the signers since I'm guessing they won't approve any re-attempts either? Not sure that made sense..

**Comment by djordon** [comment]
> > All deposit requests consumed by the bitcoin transaction are accepted by the signer.
> > All withdraw requests fulfilled by the bitcoin transaction are accepted by the signer.
> 
> @djordon hm, so based on the above, the signer not liking a single deposit/withdrawal (which maybe was accepted by all of the other signers) will cause the signer to withhold its vote on the entire sweep transaction, right? 

Yes that is correct.

> Feels kinda like the signer should sign anyway if they're part of the minority vote, otherwise if this happens continuously and sporadically it could deadlock the signers since I'm guessing they won't approve any re-attempts either? Not sure if I'm making any sense...

I understand what your saying but I don't think it is what the signers should do. This is based on a couple reasons:
1. A signer is under no obligation to sign for a transaction that it disagrees with;
2. The coordinator knows this and constructs transactions that it thinks will be accepted by enough signers to generate a signature.

With this in mind, I don't think that there are any of the risks that you describe. But if we missed something, the fix is not with having signers sign things that they believe that they shouldn't, the fix almost certainly with changing the coordinator's behavior.
