### ISSUE TITLE
Signer: stackerDB schema definition

### ISSUE THREAD

**Issue by jferrant** [stacks-network/sbtc#33]
Determine the stackerDB schema definition and how it can be used or modified to support signing rounds/signer communication 
### Message types to be written to stackerDB
**For DKG round:**
DKGBegin
DKGPublicShares,
DKGPrivateShares,
DKGEnd,

**For signing rounds:**
NonceRequest
NonceResponse
SignatureShareRequest
SignatureShareResponse

**Comment by jcnelson** [comment]
Basically, a StackerDB is a replicated array of versioned chunks.  Each chunk has exactly one writer, and chunks are replicated to each Stacks node that subscribes to this DB on a best-effort store-and-forward basis.

For example, suppose there exists a StackerDB contract with six slots, each of which can hold a chunk of up to 1 MB.  The smart contract would give Alice write access to DB slots 0, 1, and 2, and Bob access to slots 3, 4, and 5.  When Alice writes version 1 of slot 0, she posts the signed chunk to her node, and her node forwards it to other nodes subscribed to that DB.  Eventually, Bob gets a copy, and sees that slot 0 now has version 1 and contains Alice's data.

**Comment by jferrant** [comment]
First thoughts that come to mind that are a bit disorganized but I want to plant somewhere:

We will most likely have to use something like a serialized Json blob, msgpack blob, etc. that stores a vector of signer requests, signer responses per signer as we need time to elapse before overwriting a sign request or response to ensure other nodes have time to update and signers on the network have time to read them/respond to them.

In theory a specific signer will know when they have received a consensus amount of signature shares and can then can update the stacker db entry to remove sign requests/responses that are no longer being processed. This implies a signer needs to observe the blockchain for the resulting transaction to appear in the mempool or receiving a "deny consensus" or something notification

It might be worthwhile for anyone who successfully constructs a resulting transaction or reaches a consensus deny, to broadcast some sort of response to the other nodes to indicate "transaction processed successfully" not only to prevent other signers to doing extra work but to enable other signers to start clearing their caches. There still will be an instance though of that "transaction processed successfully" response needing to be cleared. Depending on how much data a signer is given this might be fine to leave accumulating for the reward cycle but I doubt it. Definitely need to tie signer internal state into this determination of what to continually write to the stackerDB entry.

As the DB is cleared each reward cycle, at least we know it will not grow indefinitely by default. However, this may have implications for later down the line but for mini it should be okay (the db should probably be cleared after a reward cycle has ended AND a hand off has been successful. Some nuance around this timing though)

**Comment by xoloki** [comment]
I implemented a full DKG round using stackerDB.  I mostly reused the message types from stacks-sbtc, with some minor variations:

https://github.com/stacks-network/stacks-blockchain/blob/stackerdb-dkg/testnet/stacks-node/src/tests/neon_integrations.rs#L11049

As noted above, stackerDB is slot based, and the contract assigns a set of slots to users by their stacks address.  Here's where I build the contract used for DKG:

https://github.com/stacks-network/stacks-blockchain/blob/stackerdb-dkg/testnet/stacks-node/src/tests/neon_integrations.rs#L11246

The signers are given IDs, and each message type gets a slot offset.  For example, DkgBegin is assigned as slot offset 0.  We keep track of which signer is acting as coordinator.  So when the coordinator writes DkgBegin to stackerDB, the correct slot is chosen like this:

https://github.com/stacks-network/stacks-blockchain/blob/stackerdb-dkg/testnet/stacks-node/src/tests/neon_integrations.rs#L11365

The signers use the same logic to poll that slot waiting for the next DkgBegin:

https://github.com/stacks-network/stacks-blockchain/blob/stackerdb-dkg/testnet/stacks-node/src/tests/neon_integrations.rs#L11379

The signers then write their DkgPublicShares:

https://github.com/stacks-network/stacks-blockchain/blob/stackerdb-dkg/testnet/stacks-node/src/tests/neon_integrations.rs#L11398

and DkgPrivateShares:

https://github.com/stacks-network/stacks-blockchain/blob/stackerdb-dkg/testnet/stacks-node/src/tests/neon_integrations.rs#L11429

The main difference in terms of the messages themselves are that we collect all DkgPublicShares into a single message, rather than sending multiple messages per key_id.
