### ISSUE TITLE
[Feature]: Missing contract check that aggregate public key is derived from signing keys

### ISSUE THREAD

**Issue by evonide** [stacks-network/sbtc#502]
# (Low) Missing contract check that aggregate public key is derived from signing keys

## 1. Description

In the bootstrap signers Clarity contract there is no check that the [aggregate public key is derived from the signing keys](https://github.com/stacks-network/sbtc/blob/3da6e48a7bc471e1edd1bd21aa24cb10d760555e/contracts/contracts/sbtc-bootstrap-signers.clar#L39-L47). See also [current version](https://github.com/stacks-network/sbtc/blob/main/contracts/contracts/sbtc-bootstrap-signers.clar). It should be added to avoid incorrect and potentially breaking updates.

**Note:** Interestingly, this check is done in the [signer code](https://github.com/stacks-network/sbtc/blob/e30e13026708456d5965f1760724d2adef452185/signer/src/stacks/contracts.rs#L428-L447), although as evident from the comment it is not implemented yet.

**Comment by djordon** [comment]
Hmmm, I'm not sure if we can do that in clarity.

**Comment by djordon** [comment]
I think the thing to do here is to remove the aggregate public key from the clarity contract. The signers don't use it and have no plans to do so, removing it will simplifies things all around.

**Comment by friedger** [comment]
How is the current signer different to the aggregate key? Is the aggregate key just the m-n multi sig that is used as current signer?

How is this check affected when using weighted key derivation?

**Comment by aldur** [comment]
IIUC: on Bitcoin, signers will use an aggregate key controlled by a threshold signature _outside_ of the Bitcoin protocol (using WSTS, which is based on front).

On Stacks, they protocol supports m-n multi-sig and that's what they'll use.

**Comment by friedger** [comment]
To verify the aggregated key we need something like https://github.com/stacks-network/stacks-core/issues/3568 ?

**Comment by djordon** [comment]
A few of points.
1. I don't think that we should derive the aggregate key from the signing set public keys. I closed a few issues about this yesterday and I think we should close this one as well.
2. Part of my comment above is wrong, we want to have the aggregate key in the smart contract because that is how the signers communicate to the world which public key should lock sBTC deposits. I don't think that we have a better mechanism for that than using a smart contract.
3. The aggregate key is currently generated randomly, and is distinct from the other public/private keys that the signers use on the Stacks side and for communication. When stacks core lands Schnorr signature support, we should probably align the bitcoin and stacks keys and always use Schnorr.
4. The only verification that we could do is that the contract caller (which is the signers) can produce a signature for the given aggregate key. But at the moment that is unnecessary since they made the contract call to begin with.

**Comment by djordon** [comment]
Closing. If anyone wants to discuss this more we can reopen.
